// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-f8fkJ-o6pNyU08XcgnWcHnEigRx6Nlo',
    appId: '1:782553620193:web:29533a5cf7ed8eb210e1a0',
    messagingSenderId: '782553620193',
    projectId: 'pasar-malam-b924a',
    authDomain: 'pasar-malam-b924a.firebaseapp.com',
    storageBucket: 'pasar-malam-b924a.firebasestorage.app',
    measurementId: 'G-2CY228RB6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANBAGf7nGwYFqh_TozG6RddbzzEefVFhg',
    appId: '1:782553620193:android:c0279bc6a9d73dfa10e1a0',
    messagingSenderId: '782553620193',
    projectId: 'pasar-malam-b924a',
    storageBucket: 'pasar-malam-b924a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBon4vRHtZ7JekO6wsUb9FZ2wZK4TWpsEg',
    appId: '1:782553620193:ios:4b72156423ac8b2310e1a0',
    messagingSenderId: '782553620193',
    projectId: 'pasar-malam-b924a',
    storageBucket: 'pasar-malam-b924a.firebasestorage.app',
    iosClientId: '782553620193-56es8ppoqrso8jrp9lp4u4n59693s1hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasarMalam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBon4vRHtZ7JekO6wsUb9FZ2wZK4TWpsEg',
    appId: '1:782553620193:ios:4b72156423ac8b2310e1a0',
    messagingSenderId: '782553620193',
    projectId: 'pasar-malam-b924a',
    storageBucket: 'pasar-malam-b924a.firebasestorage.app',
    iosClientId: '782553620193-56es8ppoqrso8jrp9lp4u4n59693s1hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasarMalam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-f8fkJ-o6pNyU08XcgnWcHnEigRx6Nlo',
    appId: '1:782553620193:web:9b8b8b8c78478a0c10e1a0',
    messagingSenderId: '782553620193',
    projectId: 'pasar-malam-b924a',
    authDomain: 'pasar-malam-b924a.firebaseapp.com',
    storageBucket: 'pasar-malam-b924a.firebasestorage.app',
    measurementId: 'G-ZGP3RL2CG7',
  );

}